export const sections = [
  {
    id: 1,
    number: 1,
    title: 'Maritime Mobile Service',
    description: 'Radio regulations, licensing, and authorities',
    examinable: true,
  },
  {
    id: 2,
    number: 2,
    title: 'Procedures',
    description: 'Phonetic alphabet, procedural words, and protocols',
    examinable: true,
  },
  {
    id: 3,
    number: 3,
    title: 'GMDSS Overview',
    description: 'Global Maritime Distress & Safety System',
    examinable: true,
  },
  {
    id: 4,
    number: 4,
    title: 'Digital Selective Calling (DSC)',
    description: 'DSC radios and Class D equipment',
    examinable: true,
  },
  {
    id: 5,
    number: 5,
    title: 'Routine Communications',
    description: 'Daily radio operations and procedures',
    examinable: true,
  },
  {
    id: 6,
    number: 6,
    title: 'Distress Communications',
    description: 'Mayday procedures and protocols',
    examinable: true,
  },
  {
    id: 7,
    number: 7,
    title: 'Urgency Communications',
    description: 'Pan Pan and priority procedures',
    examinable: true,
  },
  {
    id: 8,
    number: 8,
    title: 'Safety Communications',
    description: 'Sécurité and navigational warnings',
    examinable: true,
  },
  {
    id: 9,
    number: 9,
    title: 'Other GMDSS Equipment',
    description: 'EPIRB, SART, NAVTEX, and PLB',
    examinable: true,
  },
  {
    id: 10,
    number: 10,
    title: 'Additional Resources',
    description: 'Reference materials and study aids',
    examinable: false,
  },
];

export const quizzes = {
  1: [
    {
      id: 1,
      question: 'What certificate is required to operate a marine radio on a recreational vessel in Canada?',
      options: ['ROC(MC)', 'ROC(M)', 'Amateur Radio Certificate', 'GMDSS Certificate'],
      correctIndex: 1,
      explanation: 'The ROC(M) (Restricted Operator Certificate - Maritime) is required for operating marine radios on recreational vessels in Canada.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.4 Operator Certification (ROC(M))',
    },
    {
      id: 2,
      question: 'What is the maximum authorized power output for a VHF marine radio?',
      options: ['1 watt', '6 watts', '25 watts', '50 watts'],
      correctIndex: 2,
      explanation: 'The maximum authorized power output for VHF marine radios is 25 watts.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.1 Introduction',
    },
    {
      id: 3,
      question: 'According to IC Legal Services, what constitutes "operating" a Maritime Mobile Service radio?',
      options: ['Transmitting a message', 'Making a distress call', 'Turning it on', 'Adjusting the squelch'],
      correctIndex: 2,
      explanation: 'According to IC Legal Services, "operating" a radio means turning it on. The radio must be licensed even if never used for transmission.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.2 Regulatory Framework',
    },
    {
      id: 4,
      question: 'The approximate VHF ship-to-ship communication range is:',
      options: ['5 nautical miles', '10 nautical miles', '20 nautical miles', '50 nautical miles'],
      correctIndex: 2,
      explanation: 'The approximate VHF ship-to-ship communication range is 20 nautical miles due to line-of-sight propagation.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.1 Introduction',
    },
    {
      id: 5,
      question: 'Which of the following is NOT an authority that regulates maritime radio?',
      options: ['Innovation, Science and Economic Development Canada (IC)', 'International Telecommunications Union (ITU)', 'Transport Canada', 'International Maritime Organization (IMO)'],
      correctIndex: 2,
      explanation: 'Transport Canada does not regulate maritime radio. The regulatory bodies are IC, ITU, and IMO.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.2 Regulatory Framework',
    },
    {
      id: 6,
      question: 'A radio station licence will not be issued to anyone under the age of:',
      options: ['12 years', '14 years', '16 years', '18 years'],
      correctIndex: 2,
      explanation: 'A radio station licence will not be issued to anyone under the age of 16 years.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.3 Radio Station Licenses',
    },
    {
      id: 7,
      question: 'A Canadian vessel operating in U.S. waters requires:',
      options: ['Only an ROC(M)', 'Only a radio station licence', 'Both a radio station licence and operator\'s certificate', 'No documentation'],
      correctIndex: 2,
      explanation: 'A Canadian vessel operating in U.S. waters requires both a radio station licence and an operator\'s certificate (ROC(M)).',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.7 Required Documents',
    },
    {
      id: 8,
      question: 'The DSC Distress frequency for VHF is:',
      options: ['Channel 16 (156.800 MHz)', 'Channel 70 (156.525 MHz)', 'Channel 6 (156.300 MHz)', '2187.5 kHz'],
      correctIndex: 1,
      explanation: 'Channel 70 (156.525 MHz) is the DSC Distress frequency for VHF. Channel 16 is the voice Distress frequency.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.1 Introduction',
    },
    {
      id: 9,
      question: 'VHF communications are commonly known as:',
      options: ['Ground wave', 'Sky wave', 'Line of sight', 'Satellite'],
      correctIndex: 2,
      explanation: 'VHF communications are commonly known as "line of sight" because they require a clear, unobstructed path between transmitter and receiver.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.9 Antennas',
    },
    {
      id: 10,
      question: 'Who must carry an operator\'s certificate?',
      options: ['The vessel', 'The operator', 'The marina', 'The coast guard'],
      correctIndex: 1,
      explanation: 'The operator (person operating the radio) must carry an operator\'s certificate (ROC(M)).',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.4 Operator Certification (ROC(M))',
    },
    {
      id: 11,
      question: 'The radio silence period on MF 2182 kHz commences on the hour and half hour and extends for:',
      options: ['1 minute', '3 minutes', '5 minutes', '10 minutes'],
      correctIndex: 1,
      explanation: 'The radio silence period on MF 2182 kHz commences on the hour and half hour and extends for 3 minutes.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.1 Introduction',
    },
    {
      id: 12,
      question: 'The maximum power output of a typical handheld VHF marine radio is:',
      options: ['1 watt', '6 watts', '10 watts', '25 watts'],
      correctIndex: 1,
      explanation: 'The maximum power output of a typical handheld VHF marine radio is 6 watts.',
      reference: 'Maritime Radio Course 2019 — Section 1, 1.1 Introduction',
    },
  ],
  2: [
    {
      id: 1,
      question: 'What is the correct phonetic word for the letter "J"?',
      options: ['Juliet', 'Juliett', 'Jupiter', 'January'],
      correctIndex: 1,
      explanation: 'The correct phonetic word for "J" is "Juliett" (with double "t").',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.2 Word Spelling',
    },
    {
      id: 2,
      question: 'The procedural word "Roger" means:',
      options: ['Yes, permission granted', 'Message received and understood', 'End of conversation', 'Wait please'],
      correctIndex: 1,
      explanation: '"Roger" means "Message received and understood" - the transmission was successful.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.1 Speech Transmission Techniques',
    },
    {
      id: 3,
      question: 'The number 5800 should be transmitted as:',
      options: ['Five thousand eight hundred', 'Fifty eight hundred', 'Five eight zero zero', 'Five eight hundred'],
      correctIndex: 2,
      explanation: 'Numbers in maritime radio are transmitted digit by digit: "Five eight zero zero".',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.3 Numbers',
    },
    {
      id: 4,
      question: 'What does "Over" mean in radio procedure?',
      options: ['Conversation is ended', 'My transmission is ended, I expect a response', 'Message received', 'Wait please'],
      correctIndex: 1,
      explanation: '"Over" means your transmission is finished and you expect a response from the other station.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.1 Speech Transmission Techniques',
    },
    {
      id: 5,
      question: 'What does "Out" mean in radio procedure?',
      options: ['My transmission is ended and I expect a response', 'Conversation is ended, no response expected', 'Repeat your message', 'Message received'],
      correctIndex: 1,
      explanation: '"Out" means the conversation is ended and no response is expected. Never say "Over and Out" together.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.1 Speech Transmission Techniques',
    },
    {
      id: 6,
      question: 'A readability of "3" on the readability scale means:',
      options: ['Bad (unreadable)', 'Poor (readable now and then)', 'Fair (readable but with difficulty)', 'Good (readable)'],
      correctIndex: 2,
      explanation: 'A readability of "3" means Fair - readable but with difficulty. Scale: 1=Bad, 2=Poor, 3=Fair, 4=Good, 5=Excellent.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.8.1 Readability Scale',
    },
    {
      id: 7,
      question: 'A simplex channel:',
      options: ['Uses two different frequencies', 'Transmits and receives on the same frequency', 'Can only be used ship-to-shore', 'Is used only for distress'],
      correctIndex: 1,
      explanation: 'A simplex channel transmits and receives on the same frequency.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.6.1 Channel Groups',
    },
    {
      id: 8,
      question: 'The correct order of radio communication priority is:',
      options: ['Safety, Urgency, Distress', 'Urgency, Distress, Safety', 'Distress, Urgency, Safety', 'Distress, Safety, Urgency'],
      correctIndex: 2,
      explanation: 'The correct priority order is: Distress (highest), Urgency, Safety, then routine traffic (lowest).',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.1 Speech Transmission Techniques',
    },
    {
      id: 9,
      question: '8:30 PM expressed in 24-hour time is:',
      options: ['0830', '1830', '2030', '2230'],
      correctIndex: 2,
      explanation: '8:30 PM in 24-hour time is 20:30 (or 2030 without the colon).',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.4.1 Transmission of Time',
    },
    {
      id: 10,
      question: 'When you say "Over and Out" on the radio, this is:',
      options: ['Correct procedure', 'Used for emergencies only', 'Incorrect - you should use either Over OR Out, never both', 'Required when ending all calls'],
      correctIndex: 2,
      explanation: '"Over and Out" is incorrect procedure. Use "Over" (expect response) or "Out" (don\'t expect response), never both.',
      reference: 'Maritime Radio Course 2019 — Section 2, 2.2.1 Speech Transmission Techniques',
    },
    {
      id: 11,
      question: 'The channel designated for VHF Safety and Intership communications is:',
      options: ['Channel 16', 'Channel 70', 'Channel 6', 'Channel 22A'],
      correctIndex: 2,
      explanation: 'Channel 6 is designated for Safety and Intership communications on VHF.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
    {
      id: 12,
      question: 'When calling another station, whose name is spoken first?',
      options: ['Your own station', 'The station being called', 'The coast guard', 'It doesn\'t matter'],
      correctIndex: 1,
      explanation: 'When calling another station, the name of the station being called is spoken first (balanced calling convention).',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
  ],
  3: [
    {
      id: 1,
      question: 'GMDSS stands for:',
      options: ['General Maritime Distress and Safety System', 'Global Maritime Distress and Safety System', 'Global Marine Digital Safety System', 'General Marine Distress Signal System'],
      correctIndex: 1,
      explanation: 'GMDSS stands for Global Maritime Distress and Safety System.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.1 What is GMDSS?',
    },
    {
      id: 2,
      question: 'The DSC digital calling channel for VHF is:',
      options: ['Channel 16', 'Channel 6', 'Channel 70', 'Channel 22A'],
      correctIndex: 2,
      explanation: 'Channel 70 (156.525 MHz) is the DSC digital calling channel for VHF.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.2 Basic Concepts',
    },
    {
      id: 3,
      question: 'Sea Area A1 is defined as:',
      options: ['Within satellite coverage', 'Within range of a shore-based VHF-DSC station', 'The polar regions', 'Within range of MF-DSC stations'],
      correctIndex: 1,
      explanation: 'Sea Area A1 is defined as areas within the range of at least one shore-based VHF-DSC station.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.4 Sea Areas',
    },
    {
      id: 4,
      question: 'An MMSI number for a Canadian vessel begins with:',
      options: ['303', '316', '338', '366'],
      correctIndex: 1,
      explanation: 'Canadian vessel MMSI numbers begin with 316.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.5 Maritime Mobile Service Identity (MMSI)',
    },
    {
      id: 5,
      question: 'Pleasure craft GMDSS equipment carriage requirements are:',
      options: ['Mandatory for all vessels', 'Mandatory for vessels over 8 metres', 'Voluntary', 'Required only in Sea Area A1'],
      correctIndex: 2,
      explanation: 'GMDSS equipment carriage is voluntary for pleasure craft in Canada.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.3 Equipment Requirements',
    },
    {
      id: 6,
      question: 'An MMSI number consists of how many digits?',
      options: ['6', '7', '8', '9'],
      correctIndex: 3,
      explanation: 'An MMSI number consists of 9 digits.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.5 Maritime Mobile Service Identity (MMSI)',
    },
    {
      id: 7,
      question: 'A Group MMSI number is indicated by:',
      options: ['Two leading zeros', 'One leading zero', 'The number 8 before the country code', 'No special prefix'],
      correctIndex: 1,
      explanation: 'A Group MMSI number is indicated by one leading zero (0xxxxxxxx).',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.5 Maritime Mobile Service Identity (MMSI)',
    },
    {
      id: 8,
      question: 'A land-based station MMSI number is indicated by:',
      options: ['One leading zero', 'Two leading zeros', 'The number 8 before the country code', 'No special prefix'],
      correctIndex: 1,
      explanation: 'A land-based station MMSI number is indicated by two leading zeros (00xxxxxxx).',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.5 Maritime Mobile Service Identity (MMSI)',
    },
    {
      id: 9,
      question: 'Canada has NOT declared which Sea Area as operational?',
      options: ['Sea Area A1', 'Sea Area A2', 'Sea Area A3', 'Sea Area A4'],
      correctIndex: 1,
      explanation: 'As of January 1, 2019, neither the United States nor Canada has officially declared GMDSS Sea Area A2 operational.',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.4 Sea Areas',
    },
    {
      id: 10,
      question: 'Development of GMDSS was initiated by:',
      options: ['The ITU', 'The IMO', 'IC-SM', 'The CCG'],
      correctIndex: 1,
      explanation: 'Development of GMDSS was initiated by the International Maritime Organization (IMO).',
      reference: 'Maritime Radio Course 2019 — Section 3, 3.1 What is GMDSS?',
    },
  ],
  4: [
    {
      id: 1,
      question: 'The primary component of GMDSS is:',
      options: ['EPIRB', 'SART', 'DSC radio', 'NAVTEX'],
      correctIndex: 2,
      explanation: 'The DSC (Digital Selective Calling) radio is the primary component of GMDSS.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1 GMDSS Primary Component',
    },
    {
      id: 2,
      question: 'Class D DSC radios are the standard for:',
      options: ['Large cargo ships', 'Passenger vessels', 'Recreational boaters', 'Coast Guard stations'],
      correctIndex: 2,
      explanation: 'Class D DSC radios are the standard for recreational boaters and small vessel operators.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.3 Classes of DSC Radios',
    },
    {
      id: 3,
      question: 'To send a DSC Distress alert, you press the red Distress button for:',
      options: ['1-2 seconds', '3-5 seconds', '10 seconds', '15 seconds'],
      correctIndex: 1,
      explanation: 'To send a DSC Distress alert, press the red Distress button for 3-5 seconds.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.4 Class D DSC Capabilities',
    },
    {
      id: 4,
      question: 'DSC functions will NOT work unless:',
      options: ['The antenna is properly installed', 'An MMSI number is programmed into the radio', 'The GPS is connected', 'The radio is Class A'],
      correctIndex: 1,
      explanation: 'DSC functions require an MMSI number to be programmed into the radio to work properly.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.4 Class D DSC Capabilities',
    },
    {
      id: 5,
      question: 'You can legally test the DSC Distress function:',
      options: ['Once per month', 'Only in an emergency', 'You cannot legally test it', 'With Coast Guard permission'],
      correctIndex: 2,
      explanation: 'You cannot legally test the DSC Distress function - it must only be used in genuine distress.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.2.2 Testing DSC Functions',
    },
    {
      id: 6,
      question: 'VHF-DSC radios have a dedicated receiver for:',
      options: ['Channel 16', 'Channel 70', 'Channel 6', '2182 kHz'],
      correctIndex: 1,
      explanation: 'VHF-DSC radios have a dedicated receiver on Channel 70 (156.525 MHz) for DSC calls.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.4 Class D DSC Capabilities',
    },
    {
      id: 7,
      question: 'After sending a DSC Distress alert, the radio will retransmit automatically every:',
      options: ['30 seconds to 1 minute', '1-2 minutes', '3.5-4.5 minutes', '10-15 minutes'],
      correctIndex: 2,
      explanation: 'After sending a DSC Distress alert, the radio will retransmit automatically every 3.5-4.5 minutes.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.4 Class D DSC Capabilities',
    },
    {
      id: 8,
      question: 'Class D radios can issue a DSC Distress Acknowledgment:',
      options: ['True', 'False'],
      correctIndex: 1,
      explanation: 'Class D radios normally used by pleasure craft cannot issue Distress Acknowledgment signals - that\'s for larger vessel DSC radios.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.3 Classes of DSC Radios',
    },
    {
      id: 9,
      question: 'If no navigational equipment is interfaced with the DSC radio, vessel position must be input manually at least every:',
      options: ['1 hour', '2 hours', '4 hours', '8 hours'],
      correctIndex: 2,
      explanation: 'Without interfaced GPS, vessel position must be updated manually at least every 4 hours.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.2.1 Operational Procedures',
    },
    {
      id: 10,
      question: 'Which DSC radio class covers VHF handheld radios with GPS and DSC?',
      options: ['Class D', 'Class E', 'Class H', 'Class M'],
      correctIndex: 2,
      explanation: 'Class H DSC radios cover VHF handheld radios with integrated GPS and DSC capability.',
      reference: 'Maritime Radio Course 2019 — Section 4, 4.1.3 Classes of DSC Radios',
    },
  ],
  5: [
    {
      id: 1,
      question: 'What is the correct order for preparing to use a marine radio?',
      options: ['Switch on, Adjust squelch, Select channel, Listen, Transmit', 'Switch on, Select channel, Adjust squelch, Adjust volume, Listen, Transmit', 'Select channel, Switch on, Transmit', 'Switch on, Transmit, Adjust squelch'],
      correctIndex: 1,
      explanation: 'Correct preparation: Switch on, Select channel, Adjust squelch, Adjust volume, Listen before transmitting.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.1 General',
    },
    {
      id: 2,
      question: 'When setting the squelch, you should:',
      options: ['Set it to maximum', 'Lower it until static is heard, then increase until static just stops', 'Leave it at the factory setting', 'Turn it off completely'],
      correctIndex: 1,
      explanation: 'Properly set squelch by lowering until static is heard, then increase slightly until static just stops.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.1 General',
    },
    {
      id: 3,
      question: 'In a routine DSC call, if no acknowledgement is received within 3 minutes:',
      options: ['Send another DSC call immediately', 'Switch to Channel 16', 'The call may be repeated, but further attempts should wait at least 15 minutes', 'Send a Distress alert'],
      correctIndex: 2,
      explanation: 'If DSC call unanswered after 3 minutes, may repeat but wait at least 15 minutes before further attempts.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.2.1 Repeating a Routine DSC Call',
    },
    {
      id: 4,
      question: 'When calling another station using voice on Channel 16, if no response after two calls at two-minute intervals, you should:',
      options: ['Give up', 'Wait at least 3 minutes before calling again', 'Switch to a working channel', 'Send a Mayday'],
      correctIndex: 1,
      explanation: 'Wait at least 3 minutes (preferably 15 minutes) before attempting another call on Channel 16.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
    {
      id: 5,
      question: '"Balanced calling" means:',
      options: ['Speaking at a consistent volume', 'Saying the called station\'s name the same number of times as your own', 'Using equal time for transmitting and receiving', 'Keeping calls under 3 minutes'],
      correctIndex: 1,
      explanation: 'Balanced calling means saying the called station\'s name the same number of times as your own (e.g., 3 times each).',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
    {
      id: 6,
      question: 'When contacting a Coast Guard Radio station, you should always:',
      options: ['Use Channel 70', 'State the channel on which you are calling', 'Use only your call sign', 'Send a DSC alert first'],
      correctIndex: 1,
      explanation: 'When calling Coast Guard Radio, always state the channel on which you are calling.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
    {
      id: 7,
      question: 'After a routine call is completed, both stations must:',
      options: ['Switch to Channel 70', 'Send a DSC message', 'Sign off using their identifiers', 'Wait for coast guard confirmation'],
      correctIndex: 2,
      explanation: 'Both stations must sign off using their station identifiers to properly close the communication.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
    {
      id: 8,
      question: 'The vessel being called has which role?',
      options: ['Calling station', 'Controlling station', 'Relay station', 'No specific role'],
      correctIndex: 1,
      explanation: 'The vessel being called is the controlling station and directs the communication.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.3 Voice Procedure on Channel 16',
    },
    {
      id: 9,
      question: 'Before transmitting on the calling channel, every operator shall:',
      options: ['Send a DSC alert', 'Contact the coast guard', 'Listen for a period long enough to ensure no harmful interference', 'Switch to low power'],
      correctIndex: 2,
      explanation: 'Always listen first to ensure the channel is clear and no harmful interference will occur.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.1 General',
    },
    {
      id: 10,
      question: 'A Position Request using DSC:',
      options: ['Requires a voice call afterward', 'Is only available on Class A radios', 'Allows obtaining another vessel\'s position without voice calling', 'Must be approved by the coast guard'],
      correctIndex: 2,
      explanation: 'DSC Position Request allows you to ask for another vessel\'s position digitally without voice communication.',
      reference: 'Maritime Radio Course 2019 — Section 5, 5.7 Group Calling Using DSC',
    },
  ],
  6: [
    {
      id: 1,
      question: 'The Distress signal "Mayday" indicates:',
      options: ['A vessel needs a tow', 'There is a medical emergency', 'A vessel is threatened by grave and imminent danger and requires immediate assistance', 'Bad weather is approaching'],
      correctIndex: 2,
      explanation: 'Mayday indicates grave and imminent danger requiring immediate assistance.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.1 Distress Signal Definition',
    },
    {
      id: 2,
      question: 'In a Distress call, "Mayday" is spoken:',
      options: ['Once', 'Twice', 'Three times', 'As many times as needed'],
      correctIndex: 2,
      explanation: 'In the initial Distress call, "Mayday" is spoken three times to ensure recognition.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.4 Distress Call and Message',
    },
    {
      id: 3,
      question: 'The Distress call shall be sent on whose authority?',
      options: ['Any crew member', 'The radio operator', 'The person in command of the vessel', 'The coast guard'],
      correctIndex: 2,
      explanation: 'The Distress call must be authorized by the person in command (captain/skipper) of the vessel.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.2.1 Control of Distress Traffic',
    },
    {
      id: 4,
      question: 'In the Distress MESSAGE (after the initial call), "Mayday" is spoken:',
      options: ['Three times', 'Twice', 'Once', 'Not at all'],
      correctIndex: 2,
      explanation: 'In the Distress message that follows the initial call, "Mayday" is spoken only once.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.4 Distress Call and Message',
    },
    {
      id: 5,
      question: '"Seelonce Mayday" is the command used by:',
      options: ['Any station', 'The coast guard only', 'The vessel in distress', 'Aircraft'],
      correctIndex: 2,
      explanation: '"Seelonce Mayday" (Silence Mayday) is used by the vessel in distress to impose silence on other stations.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.8 Imposing Silence',
    },
    {
      id: 6,
      question: '"Seelonce Distress" is used by:',
      options: ['The vessel in distress', 'Stations OTHER than the vessel in distress', 'Only the coast guard', 'No one - it\'s not a real command'],
      correctIndex: 1,
      explanation: '"Seelonce Distress" is used by stations OTHER than the vessel in distress to impose silence.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.8.1 Imposing Silence by Vessel Other Than Vessel in Distress',
    },
    {
      id: 7,
      question: '"Seelonce Feenee" means:',
      options: ['Radio silence is imposed', 'The distress situation is cancelled / normal service may resume', 'Urgency traffic in progress', 'Safety message to follow'],
      correctIndex: 1,
      explanation: '"Seelonce Feenee" (Silence Fini - Silence Finished) means the distress situation is cancelled and normal service resumes.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.9 Cancellation of Distress',
    },
    {
      id: 8,
      question: 'When receiving a DSC Distress alert, boaters should:',
      options: ['Immediately transmit a voice acknowledgement', 'Send their own DSC Distress alert', 'Wait for Coast Guard Radio to acknowledge first, then assist if requested', 'Ignore it if not nearby'],
      correctIndex: 2,
      explanation: 'Wait for CGR acknowledgement first. Only offer assistance if requested. Don\'t interfere with distress traffic.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.5 Action on Receipt of DSC Distress Alert',
    },
    {
      id: 9,
      question: 'A vessel making a Mayday Relay call must NOT:',
      options: ['Use Channel 16', 'State their own vessel name', 'Precede it with a DSC Distress alert', 'Include the distressed vessel\'s position'],
      correctIndex: 2,
      explanation: 'A Mayday Relay should NOT be preceded with DSC - use voice only to relay the Mayday.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.6 Mayday Relay',
    },
    {
      id: 10,
      question: 'The Distress call and message should include all of the following EXCEPT:',
      options: ['Vessel name and position', 'Nature of distress', 'Number of persons on board', 'Insurance policy number'],
      correctIndex: 3,
      explanation: 'Insurance policy number is NOT needed in a Distress call. Include vessel name, position, nature of distress, and persons on board.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.4.1 Example of a Distress Call and Message',
    },
    {
      id: 11,
      question: 'In Distress traffic, the word "Mayday" spoken once shall precede:',
      options: ['Only the initial call', 'All transmissions related to the distress', 'Only acknowledgements', 'Nothing after the initial call'],
      correctIndex: 1,
      explanation: 'After the initial call, "Mayday" spoken once precedes the Distress message and all related transmissions.',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.4 Distress Call and Message',
    },
    {
      id: 12,
      question: 'Control of Distress traffic is the responsibility of:',
      options: ['Always the coast guard', 'The vessel in distress, unless delegated', 'The nearest vessel', 'The ITU'],
      correctIndex: 1,
      explanation: 'The vessel in distress controls the Distress traffic, unless they delegate control to another station (usually Coast Guard Radio).',
      reference: 'Maritime Radio Course 2019 — Section 6, 6.2.1 Control of Distress Traffic',
    },
  ],
  7: [
    {
      id: 1,
      question: 'The Urgency signal is:',
      options: ['Mayday', 'Pan Pan', 'Sécurité', 'Seelonce'],
      correctIndex: 1,
      explanation: 'The Urgency signal is "Pan Pan" (transmitted three times in the call).',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.3 Urgency Signal',
    },
    {
      id: 2,
      question: '"Pan Pan" indicates:',
      options: ['Grave and imminent danger', 'A very urgent message concerning safety of ship, aircraft, vehicle or person', 'A navigational warning', 'A weather forecast'],
      correctIndex: 1,
      explanation: '"Pan Pan" indicates an urgent situation concerning safety, but not grave and imminent danger (that\'s Mayday).',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.3 Urgency Signal',
    },
    {
      id: 3,
      question: 'Stations hearing an Urgency signal must continue to listen for at least:',
      options: ['1 minute', '3 minutes', '5 minutes', '15 minutes'],
      correctIndex: 1,
      explanation: 'Stations must listen for at least 3 minutes after hearing an Urgency signal.',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.1 Priority',
    },
    {
      id: 4,
      question: 'The Urgency signal has priority over all communications except:',
      options: ['Safety', 'Routine', 'Distress', 'Direction-finding'],
      correctIndex: 2,
      explanation: 'Urgency has priority over all communications except Distress (which is highest priority).',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.1 Priority',
    },
    {
      id: 5,
      question: 'An Urgency call should normally be addressed to:',
      options: ['The nearest vessel', 'All Stations', 'Coast Guard only', 'The vessel needing help'],
      correctIndex: 1,
      explanation: 'An Urgency call is normally addressed to "All Stations" to ensure wide coverage.',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.4 Urgency Call and Message',
    },
    {
      id: 6,
      question: 'The Urgency call is sent on:',
      options: ['Any available channel', 'Channel 70 only', 'VHF Channel 16 and/or 2182 kHz', 'Channel 6'],
      correctIndex: 2,
      explanation: 'Urgency calls are sent on Channel 16 (VHF) and/or 2182 kHz (MF).',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.2 Frequencies to be Used',
    },
    {
      id: 7,
      question: 'To cancel an Urgency situation, the correct phrase is:',
      options: ['Seelonce Feenee', 'Pan Pan Cancel', 'Urgency Ended', 'Roger Out'],
      correctIndex: 2,
      explanation: 'To cancel Urgency traffic, broadcast "Urgency Ended" addressed to All Stations. "Seelonce Feenee" is used only to cancel Distress silence.',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.4.2 Cancellation of Urgency',
    },
    {
      id: 8,
      question: 'The cancellation of an Urgency call shall be addressed to:',
      options: ['The coast guard only', 'The vessel that caused the urgency', 'All Stations, regardless of to whom the initial call was sent', 'Only vessels that responded'],
      correctIndex: 2,
      explanation: 'Urgency cancellation is addressed to All Stations, the same as the initial call.',
      reference: 'Maritime Radio Course 2019 — Section 7, 7.4.2 Cancellation of Urgency',
    },
  ],
  8: [
    {
      id: 1,
      question: 'The Safety signal is:',
      options: ['Mayday', 'Pan Pan', 'Sécurité', 'Alert'],
      correctIndex: 2,
      explanation: 'The Safety signal is "Sécurité" (transmitted three times in the call).',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
    {
      id: 2,
      question: 'A Safety call indicates:',
      options: ['A vessel is in distress', 'An important navigational or meteorological warning', 'A medical emergency', 'A routine message'],
      correctIndex: 1,
      explanation: 'Safety calls are for important navigational or meteorological warnings to other vessels.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
    {
      id: 3,
      question: 'The Safety call is made on:',
      options: ['Channel 6', 'Channel 16', 'Channel 70', 'Any working channel'],
      correctIndex: 1,
      explanation: 'The initial Safety call is made on Channel 16 to get attention, then the message is sent on a working channel.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
    {
      id: 4,
      question: 'The Safety MESSAGE (after the call on Ch 16) should be sent on:',
      options: ['Channel 16', 'A suitable working channel (e.g., Channel 6)', 'Channel 70', '2182 kHz only'],
      correctIndex: 1,
      explanation: 'After the initial call on Channel 16, the Safety message is transmitted on a suitable working channel like Channel 6.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.3 Example of a VHF Safety Call',
    },
    {
      id: 5,
      question: 'Safety calls are normally:',
      options: ['Addressed to a specific vessel', 'Broadcasts that do not expect a reply', 'Only sent by coast guard', 'Followed by a DSC alert'],
      correctIndex: 1,
      explanation: 'Safety calls are broadcasts that do not expect a reply - they inform all listening stations.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.4 Responding to a Safety Alert or Call',
    },
    {
      id: 6,
      question: 'The Safety signal has priority over all communications except:',
      options: ['Routine calls', 'Distress and Urgency', 'Only Distress', 'Direction-finding'],
      correctIndex: 1,
      explanation: 'Safety has priority over routine traffic but below Distress and Urgency.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.1 Priority',
    },
    {
      id: 7,
      question: 'It is recommended that vessels NOT send a DSC Safety alert because:',
      options: ['It\'s illegal', 'DSC can\'t handle Safety alerts', 'It would alert all vessels within range when the message is usually only relevant to a small area', 'Channel 70 is reserved for Distress only'],
      correctIndex: 2,
      explanation: 'DSC Safety alerts alert all vessels in range, but Safety messages are usually relevant only to a local area. Use voice on Channel 16.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
    {
      id: 8,
      question: 'Channel 6 is designated as:',
      options: ['A Distress channel', 'A duplex channel', 'A Safety and Intership channel', 'A weather channel'],
      correctIndex: 2,
      explanation: 'Channel 6 (156.300 MHz) is designated for Safety and Intership communications.',
      reference: 'Maritime Radio Course 2019 — Section 8, 8.2 Procedures',
    },
  ],
  9: [
    {
      id: 1,
      question: 'An EPIRB operates on:',
      options: ['121.5 MHz', '156.8 MHz', '406 MHz', '518 kHz'],
      correctIndex: 2,
      explanation: 'Modern EPIRBs operate on 406 MHz and are detected by COSPAS-SARSAT satellite system.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.1 Emergency Position Indicating Radio Beacon (EPIRB)',
    },
    {
      id: 2,
      question: 'A Category 1 EPIRB:',
      options: ['Must be activated manually', 'Can activate automatically when submerged', 'Is only for commercial vessels', 'Does not include GPS'],
      correctIndex: 1,
      explanation: 'A Category 1 EPIRB can activate automatically when exposed to saltwater (vessel sinking).',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.1 Emergency Position Indicating Radio Beacon (EPIRB)',
    },
    {
      id: 3,
      question: 'The EPIRB homing signal operates on:',
      options: ['406 MHz', '121.5 MHz', '518 kHz', '156.525 MHz'],
      correctIndex: 1,
      explanation: 'The EPIRB homing signal (for rescue phase) operates on 121.5 MHz.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.1 Emergency Position Indicating Radio Beacon (EPIRB)',
    },
    {
      id: 4,
      question: 'EPIRBs must be registered with:',
      options: ['The coast guard', 'The Canadian Beacon Registry', 'Innovation, Science and Economic Development Canada', 'The IMO'],
      correctIndex: 1,
      explanation: 'All EPIRBs must be registered with the Canadian Beacon Registry.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.1 Emergency Position Indicating Radio Beacon (EPIRB)',
    },
    {
      id: 5,
      question: 'A SART responds to what type of radar?',
      options: ['S-band radar', 'X-band 9 GHz radar', 'Broadband radar', 'Any radar type'],
      correctIndex: 1,
      explanation: 'A SART (Search and Rescue Transponder) responds to X-band 9 GHz radar.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.3 Search and Rescue Transponder (SART)',
    },
    {
      id: 6,
      question: 'A SART generates how many blips on a radar screen?',
      options: ['3', '6', '12', '24'],
      correctIndex: 2,
      explanation: 'A SART generates 12 blips in a distinctive pattern on radar screens, making it easy to identify.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.3 Search and Rescue Transponder (SART)',
    },
    {
      id: 7,
      question: 'As a rescue vessel approaches a SART, the blips change to:',
      options: ['Larger blips', 'Wide arcs, then complete circles', 'A single large dot', 'They disappear'],
      correctIndex: 1,
      explanation: 'As the rescuing vessel gets closer, the 12 blips transition to arcs, then complete circles on the radar.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.3 Search and Rescue Transponder (SART)',
    },
    {
      id: 8,
      question: 'NAVTEX operates on:',
      options: ['406 MHz', '156.8 MHz', '518 kHz', '2182 kHz'],
      correctIndex: 2,
      explanation: 'NAVTEX (Navigational Telex) operates on 518 kHz and provides automated marine weather and safety information.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.5 NAVTEX',
    },
    {
      id: 9,
      question: 'A Personal Locator Beacon (PLB):',
      options: ['Activates automatically when submerged', 'Can only be activated manually', 'Does not need to be registered', 'Uses satellite phone technology'],
      correctIndex: 1,
      explanation: 'A PLB is a personal rescue device that must be manually activated by the person in distress.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.1 Emergency Position Indicating Radio Beacon (EPIRB)',
    },
    {
      id: 10,
      question: 'The typical range of NAVTEX transmissions is:',
      options: ['20-50 nautical miles', '100-200 nautical miles', '250-400 nautical miles', '1000+ nautical miles'],
      correctIndex: 2,
      explanation: 'NAVTEX transmissions typically reach 250-400 nautical miles under normal conditions.',
      reference: 'Maritime Radio Course 2019 — Section 9, 9.5 NAVTEX',
    },
  ],
};

export const sectionContent = {
  1: {
    title: 'Maritime Mobile Service',
    keyPoints: [
      {
        heading: 'ROC(M) Certification',
        content: 'The Restricted Operator Certificate - Maritime (ROC(M)) is required to operate a marine radio on recreational vessels in Canada. It demonstrates knowledge of radio procedures, safety, and Canadian maritime regulations.',
      },
      {
        heading: 'Radio Station Licence',
        content: 'In addition to the operator\'s certificate (ROC(M)), the vessel must have a Radio Station Licence. The operator must carry the certificate; the vessel must carry the licence. A radio station licence will not be issued to anyone under 16 years old.',
      },
      {
        heading: 'Regulatory Authorities',
        content: 'Maritime radio is regulated by Innovation, Science and Economic Development Canada (IC) through the Radio Regulations, the International Telecommunications Union (ITU), the International Maritime Organization (IMO), and the Canadian Coast Guard (CCG).',
      },
      {
        heading: 'What Constitutes Operating',
        content: 'According to IC Legal Services, "operating" a Maritime Mobile Service radio means turning it on. The radio must be licensed even if never used for transmission.',
      },
      {
        heading: 'VHF Communication Range',
        content: 'The approximate VHF ship-to-ship communication range is 20 nautical miles. This is due to line-of-sight propagation - VHF signals follow the curvature of the Earth and cannot bend significantly around obstacles.',
      },
      {
        heading: 'Channel 16 and Channel 70',
        content: 'Channel 16 (156.800 MHz) is the designated VHF Distress and safety calling channel for voice communications. Channel 70 (156.525 MHz) is the DSC digital calling channel with a dedicated receiver on DSC-equipped radios.',
      },
      {
        heading: 'VHF Power Output',
        content: 'The maximum authorized power output for a VHF marine radio is 25 watts. Handheld VHF marine radios typically output a maximum of 6 watts.',
      },
      {
        heading: 'Radio Silence Periods',
        content: 'On MF 2182 kHz, radio silence periods begin on the hour and half hour and extend for 3 minutes. During these periods, only distress communications are permitted.',
      },
      {
        heading: 'Secrecy of Communications',
        content: 'Information obtained from listening to radio communications must not be disclosed or used, except with the consent of persons involved. This applies to all maritime radio traffic.',
      },
      {
        heading: 'Required Documents',
        content: 'To legally operate a marine radio, you must have: (1) A valid ROC(M) certificate (operator must carry), (2) A Radio Station Licence (posted on the vessel), (3) MMSI number (for DSC-equipped vessels)',
      },
    ],
  },
  2: {
    title: 'Procedures',
    keyPoints: [
      {
        heading: 'Phonetic Alphabet',
        content: 'Letters are transmitted using standard phonetic words to ensure clarity. Each letter has a unique phonetic word (Alpha, Bravo, Charlie, etc.). Numbers are transmitted digit-by-digit (5800 = "Five Eight Zero Zero")',
      },
      {
        heading: 'Procedural Words',
        content: 'Key procedural words include: Roger (message received), Wilco (will comply), Over (my transmission ends, expect response), Out (conversation ends, no response expected). Never say "Over and Out" - use either one or the other.',
      },
      {
        heading: 'Readability Scale',
        content: 'Readability is rated 1-5: (1) Bad - unreadable, (2) Poor - readable now and then, (3) Fair - readable but with difficulty, (4) Good - readable, (5) Excellent - perfectly readable.',
      },
      {
        heading: 'Communication Priority',
        content: 'Radio communication priorities in descending order: (1) Distress, (2) Urgency, (3) Safety, (4) Routine. Lower priority traffic must wait for higher priority communications to complete.',
      },
      {
        heading: '24-Hour Time',
        content: 'Maritime radio uses 24-hour time format (0000 to 2359). Example: 8:30 PM = 2030 (or 20:30 with colon). Always use four digits without a colon in radio transmission.',
      },
      {
        heading: 'Simplex vs Duplex',
        content: 'Simplex channels transmit and receive on the same frequency. Duplex channels use two different frequencies - one for transmit, one for receive. Most maritime channels are simplex.',
      },
      {
        heading: 'Balanced Calling',
        content: 'When calling another station, say the called station\'s name the same number of times as your own (e.g., "Charlie Charlie Charlie, this is Echo Echo Echo").',
      },
      {
        heading: 'VHF Channels',
        content: 'Channel 16 (156.800 MHz) is the primary calling and distress channel. Channel 6 (156.300 MHz) is for Safety and Intership communications. Channel 9 is for commercial traffic.',
      },
      {
        heading: 'Listening Before Transmitting',
        content: 'Always listen first to ensure the channel is clear before transmitting. This prevents harmful interference and ensures you don\'t interrupt important communications.',
      },
      {
        heading: 'Radio Checks',
        content: 'A radio check confirms your radio is transmitting clearly. Request: "Station A, this is Station B, radio check." Response should include readability number and signal strength assessment.',
      },
    ],
  },
  3: {
    title: 'GMDSS Overview',
    keyPoints: [
      {
        heading: 'What is GMDSS',
        content: 'The Global Maritime Distress and Safety System (GMDSS) is an internationally agreed-upon set of safety procedures, systems, and devices for alerting rescue authorities and for coordinating rescue efforts in response to maritime distress situations.',
      },
      {
        heading: 'GMDSS Components',
        content: 'Primary components include: DSC (Digital Selective Calling) radios, EPIRB (Emergency Position Indicating Radio Beacon), SART (Search and Rescue Transponder), and NAVTEX (Navigational Telex) for weather and safety information.',
      },
      {
        heading: 'Sea Areas',
        content: 'GMDSS defines four Sea Areas: A1 (within range of shore-based VHF-DSC), A2 (within range of MF-DSC), A3 (within range of INMARSAT satellite), A4 (polar regions). As of January 1, 2019, neither Canada nor the United States has officially declared Sea Area A2 operational.',
      },
      {
        heading: 'MMSI Numbers',
        content: 'MMSI (Maritime Mobile Service Identity) is a unique 9-digit number assigned to vessels with DSC radios. Canadian MMSIs begin with 316. MMSI identifies the vessel in DSC communications.',
      },
      {
        heading: 'Group MMSI',
        content: 'A Group MMSI (one leading zero) is used for simultaneous DSC calls to multiple vessels. For example, all fishing vessels in a region might share a Group MMSI.',
      },
      {
        heading: 'Land-Based Station MMSI',
        content: 'Land-based Coast Guard Radio stations have MMSI numbers indicated by two leading zeros (00xxxxxxx).',
      },
      {
        heading: 'Pleasure Craft Carriage Requirements',
        content: 'GMDSS equipment carriage is VOLUNTARY for pleasure craft in Canada, unlike commercial vessels where it is mandatory. Many recreational boaters still equip with DSC radios for safety.',
      },
      {
        heading: 'DSC Digital Calling',
        content: 'Channel 70 (156.525 MHz) is dedicated for DSC digital calling on VHF. All DSC-equipped radios have a dedicated receiver on this channel.',
      },
      {
        heading: 'GMDSS Development',
        content: 'GMDSS was developed by the International Maritime Organization (IMO) as a successor to the older MCTS (Maritime Communication Tracking System) to improve distress communication reliability.',
      },
      {
        heading: 'Video Resources',
        content: 'View "Overview of GMDSS" on YouTube for additional visual information about system components and procedures.',
      },
    ],
  },
  4: {
    title: 'Digital Selective Calling (DSC)',
    keyPoints: [
      {
        heading: 'What is DSC',
        content: 'Digital Selective Calling (DSC) is a digital radio communications system that allows vessels to automatically call specific stations by pressing buttons rather than speaking. DSC is the primary component of GMDSS.',
      },
      {
        heading: 'Class D Radios',
        content: 'Class D DSC radios are the standard for recreational boaters and small vessel operators. They are compact, relatively affordable, and suitable for pleasure craft operations.',
      },
      {
        heading: 'MMSI Requirement',
        content: 'A valid MMSI number MUST be programmed into your DSC radio for it to function. Without an MMSI, the radio cannot send DSC distress alerts or make DSC calls.',
      },
      {
        heading: 'Sending a DSC Distress Alert',
        content: 'To send a DSC Distress alert, press and hold the red Distress button for 3-5 seconds. The radio will transmit your vessel\'s information (name, MMSI, position if GPS-equipped) to all nearby stations and rescue coordination centers.',
      },
      {
        heading: 'Channel 70 Receiver',
        content: 'DSC-equipped VHF radios have a dedicated receiver on Channel 70 (156.525 MHz) that monitors for DSC alerts even when the radio is tuned to another channel.',
      },
      {
        heading: 'Distress Button Testing',
        content: 'You CANNOT legally test the DSC Distress button - it can only be used in a genuine distress emergency. Testing would alert rescue services unnecessarily and could result in fines.',
      },
      {
        heading: 'Distress Alert Retransmission',
        content: 'After sending a DSC Distress alert, the radio will automatically retransmit the alert every 3.5-4.5 minutes until cancelled or acknowledged.',
      },
      {
        heading: 'Class D vs Other Classes',
        content: 'Class D radios are for pleasure craft. Class A/B radios (commercial vessels) can issue Distress Acknowledgments. Class H covers VHF handheld radios with integrated GPS and DSC.',
      },
      {
        heading: 'Position Update Requirements',
        content: 'If your DSC radio does not have GPS interfaced, you must manually update the vessel\'s position in the radio at least every 4 hours to ensure accurate location information in case of distress.',
      },
      {
        heading: 'Video Resources',
        content: 'See "DSC Radios" by Icom USA and "Overview of DSC" by Icom UK on YouTube for detailed demonstrations of DSC radio operation.',
      },
    ],
  },
  5: {
    title: 'Routine Communications',
    keyPoints: [
      {
        heading: 'Radio Preparation Steps',
        content: '(1) Switch on the radio, (2) Select the desired channel, (3) Adjust the squelch, (4) Adjust the volume, (5) LISTEN for at least 30 seconds, (6) Then transmit. Always listen first!',
      },
      {
        heading: 'Setting the Squelch',
        content: 'The squelch prevents static noise when no signal is present. Adjust by lowering the squelch until you hear static, then raise it slightly until the static just stops. This setting receives the weakest signals.',
      },
      {
        heading: 'Balanced Calling',
        content: 'Say the station you\'re calling 3 times, then your station 3 times: "Mary Mary Mary, this is John John John." This balanced approach ensures both stations are heard.',
      },
      {
        heading: 'DSC Routine Calls',
        content: 'In routine DSC calling, if no acknowledgement is received within 3 minutes, the call may be repeated. However, further calling attempts should wait at least 15 minutes.',
      },
      {
        heading: 'Voice Calling on Channel 16',
        content: 'When calling another station using voice on Channel 16, if no response after two calls at 2-minute intervals, wait at least 3 minutes (preferably 15) before calling again.',
      },
      {
        heading: 'Contacting Coast Guard',
        content: 'When contacting Coast Guard Radio, always state the channel on which you are calling. Listen on that channel and speak clearly.',
      },
      {
        heading: 'Ending Communications',
        content: 'Both stations must sign off using their station identifiers at the end of the communication. Example: "This is John, out" or "John clear."',
      },
      {
        heading: 'Controlling vs Calling Station',
        content: 'The station being called is the controlling station - they direct the communication and determine when to switch channels or end the call.',
      },
      {
        heading: 'Position Requests',
        content: 'DSC Position Request allows you to ask another vessel for their current position digitally without voice communication. The vessel can respond with their GPS coordinates automatically.',
      },
      {
        heading: 'Video Resources',
        content: 'Review "Overview of DSC" by Icom UK on YouTube for demonstration of routine DSC calling and voice communications on VHF.',
      },
    ],
  },
  6: {
    title: 'Distress Communications',
    keyPoints: [
      {
        heading: 'Mayday Definition',
        content: 'Mayday indicates that a vessel is threatened by grave and imminent danger and requires immediate assistance from rescue authorities or other vessels. It is the highest priority radio signal.',
      },
      {
        heading: 'Authority for Distress',
        content: 'Only the person in command (captain/skipper) of the vessel has the authority to declare a distress situation and send a Mayday. The person in command must make this decision.',
      },
      {
        heading: 'Initial Distress Call',
        content: 'The distress call begins with "Mayday" spoken THREE times, followed by "This is" and the vessel name spoken THREE times. This ensures recognition of the distress situation.',
      },
      {
        heading: 'Distress Message Content',
        content: 'The Distress message includes: (1) "Mayday" (once), (2) Vessel name and call sign, (3) Position, (4) Nature of distress, (5) Type and number of persons on board, (6) Any assistance available.',
      },
      {
        heading: 'Seelonce Mayday',
        content: '"Seelonce Mayday" (Silence Mayday) is the command used by the vessel in distress to order all other stations into radio silence except those directly involved in the rescue.',
      },
      {
        heading: 'Seelonce Distress',
        content: '"Seelonce Distress" is used by stations OTHER than the vessel in distress (e.g., Coast Guard Radio or a rescue ship) to impose silence on non-essential traffic.',
      },
      {
        heading: 'Seelonce Feenee',
        content: '"Seelonce Feenee" (Silence Fini - meaning "Silence Finished") means the distress situation has been cancelled and normal radio service may resume.',
      },
      {
        heading: 'Responding to DSC Distress Alert',
        content: 'When receiving a DSC Distress alert, DO NOT immediately transmit a voice acknowledgement. Wait for Coast Guard Radio to acknowledge first, then offer assistance only if requested.',
      },
      {
        heading: 'Mayday Relay',
        content: 'A vessel relaying a Mayday call for another vessel says "Mayday Relay" three times followed by the distressed vessel\'s details. It should NOT be preceded by a DSC alert.',
      },
      {
        heading: 'Distress Control',
        content: 'Control of distress traffic remains with the vessel in distress unless they delegate it (usually to Coast Guard Radio). All other stations must follow the controlling station\'s directions.',
      },
    ],
  },
  7: {
    title: 'Urgency Communications',
    keyPoints: [
      {
        heading: 'Pan Pan Definition',
        content: '"Pan Pan" is the urgency signal indicating a very urgent message concerning the safety of a ship, aircraft, person, or vehicle. It is below Distress in priority but above Safety.',
      },
      {
        heading: 'When to Use Pan Pan',
        content: 'Use Pan Pan when there is an urgent situation that is serious but does not require IMMEDIATE assistance. Examples: serious illness requiring immediate medical advice, propulsion problems, water in the hull.',
      },
      {
        heading: 'Pan Pan Transmission',
        content: 'The urgency call begins with "Pan Pan" spoken THREE times, followed by "All Stations", then "This is" and your vessel name.',
      },
      {
        heading: 'Listening Requirement',
        content: 'All stations hearing a Pan Pan signal must continue to listen for at least 3 minutes and not transmit on that channel unless directly involved in the urgency traffic.',
      },
      {
        heading: 'Priority Level',
        content: 'Urgency traffic has priority over all communications except Distress. All routine traffic must cease, and stations must listen without transmitting.',
      },
      {
        heading: 'Addressed to All Stations',
        content: 'Pan Pan calls are normally broadcast to "All Stations" on Channel 16 to ensure all nearby vessels and Coast Guard receive the urgency information.',
      },
      {
        heading: 'Pan Pan Cancellation',
        content: 'To end urgency traffic, the vessel broadcasts "Urgency Ended" addressed to All Stations on the same channel used for the initial Pan Pan.',
      },
      {
        heading: 'Cancellation Scope',
        content: 'The urgency cancellation must be addressed to All Stations (same as the initial call) to ensure all listening vessels know the urgency situation is over.',
      },
      {
        heading: 'Pan Pan vs Mayday',
        content: 'Pan Pan = serious safety issue, Coast Guard notified, assistance likely needed, some time available. Mayday = grave danger, immediate assistance required NOW.',
      },
      {
        heading: 'Urgent Medical Advice',
        content: 'Pan Pan is commonly used to request urgent medical advice. Contact Coast Guard Radio with patient details - they can connect you with medical personnel.',
      },
    ],
  },
  8: {
    title: 'Safety Communications',
    keyPoints: [
      {
        heading: 'Sécurité Definition',
        content: '"Sécurité" (pronounced "Say-cure-ee-tay") is the safety signal indicating an important navigational or meteorological warning that may affect other vessels.',
      },
      {
        heading: 'Safety Message Examples',
        content: 'Safety messages include: navigation hazards (wreck, debris), storms or severe weather, ice warnings, unusual sea conditions, or other dangers to navigation.',
      },
      {
        heading: 'Sécurité Transmission',
        content: 'The safety call begins with "Sécurité" spoken THREE times, followed by "All Stations", then your station identifier and the warning information.',
      },
      {
        heading: 'Channel 16 Initial Call',
        content: 'The initial Safety call to get attention is made on Channel 16 (156.800 MHz). This alerts all stations that important safety information will follow.',
      },
      {
        heading: 'Working Channel for Message',
        content: 'After the initial call on Channel 16, switch to a suitable working channel (commonly Channel 6) to broadcast the detailed safety information.',
      },
      {
        heading: 'Broadcast Nature',
        content: 'Safety calls are broadcasts to All Stations and do NOT expect a reply. They inform all listening vessels of potential hazards.',
      },
      {
        heading: 'Priority Level',
        content: 'Safety traffic has priority over routine communications but is below Distress and Urgency. Routine traffic must stand by for safety information.',
      },
      {
        heading: 'Why No DSC Safety Alert',
        content: 'It is recommended to NOT send a DSC Safety alert because it would alert ALL vessels within DSC range, but the safety information is usually only relevant to a small geographic area. Use voice on Channel 16 instead.',
      },
      {
        heading: 'Channel 6 Designation',
        content: 'Channel 6 (156.300 MHz) is designated as the Safety and Intership communications channel. It\'s the standard working channel for detailed safety information.',
      },
      {
        heading: 'Listening Requirement',
        content: 'Although stations must monitor for safety traffic, a minimum listening period is not specified (unlike Urgency which requires 3 minutes).',
      },
    ],
  },
  9: {
    title: 'Other GMDSS Equipment',
    keyPoints: [
      {
        heading: 'EPIRB Overview',
        content: 'An EPIRB (Emergency Position Indicating Radio Beacon) is a device that transmits a distress signal to rescue authorities via satellite when activated.',
      },
      {
        heading: 'EPIRB Frequency',
        content: 'Modern EPIRBs transmit on 406 MHz, which is detected by the COSPAS-SARSAT satellite system. This provides accurate vessel location to rescue services.',
      },
      {
        heading: 'Category 1 EPIRB',
        content: 'Category 1 EPIRBs can activate automatically when immersed in saltwater (e.g., vessel sinking). Manual activation is also available. They include GPS location data.',
      },
      {
        heading: 'EPIRB Registration',
        content: 'All EPIRBs must be registered with the Canadian Beacon Registry so rescue authorities can identify the vessel when an alert is received.',
      },
      {
        heading: 'EPIRB Homing Signal',
        content: 'After satellite detection, the EPIRB transmits on 121.5 MHz for homing - this allows rescue aircraft to locate the actual beacon and distressed vessel.',
      },
      {
        heading: 'SART Overview',
        content: 'A SART (Search and Rescue Transponder) is a radar transponder that responds to rescue ship and aircraft radar signals, making the vessel visible on radar displays.',
      },
      {
        heading: 'SART Frequency',
        content: 'SART responds specifically to X-band 9 GHz radar, which is standard on rescue vessels and aircraft.',
      },
      {
        heading: 'SART Radar Pattern',
        content: 'When activated, a SART displays as 12 distinctive blips in a line on the rescuer\'s radar screen, making it immediately recognizable as a SART transmission.',
      },
      {
        heading: 'SART Range Closure',
        content: 'As the rescue vessel approaches the SART, the 12 blips gradually form into arcs, then eventually appear as complete circles on the radar display.',
      },
      {
        heading: 'NAVTEX System',
        content: 'NAVTEX (Navigational Telex) operates on 518 kHz and provides automated broadcasts of maritime weather forecasts, gale warnings, navigational warnings, and safety information.',
      },
    ],
  },
};

export const phoneticAlphabet = [
  { letter: 'A', word: 'Alpha' },
  { letter: 'B', word: 'Bravo' },
  { letter: 'C', word: 'Charlie' },
  { letter: 'D', word: 'Delta' },
  { letter: 'E', word: 'Echo' },
  { letter: 'F', word: 'Foxtrot' },
  { letter: 'G', word: 'Golf' },
  { letter: 'H', word: 'Hotel' },
  { letter: 'I', word: 'India' },
  { letter: 'J', word: 'Juliett' },
  { letter: 'K', word: 'Kilo' },
  { letter: 'L', word: 'Lima' },
  { letter: 'M', word: 'Mike' },
  { letter: 'N', word: 'November' },
  { letter: 'O', word: 'Oscar' },
  { letter: 'P', word: 'Papa' },
  { letter: 'Q', word: 'Quebec' },
  { letter: 'R', word: 'Romeo' },
  { letter: 'S', word: 'Sierra' },
  { letter: 'T', word: 'Tango' },
  { letter: 'U', word: 'Uniform' },
  { letter: 'V', word: 'Victor' },
  { letter: 'W', word: 'Whiskey' },
  { letter: 'X', word: 'X-ray' },
  { letter: 'Y', word: 'Yankee' },
  { letter: 'Z', word: 'Zulu' },
];

export const numbers = [
  { digit: '0', word: 'Zero' },
  { digit: '1', word: 'One' },
  { digit: '2', word: 'Two' },
  { digit: '3', word: 'Three' },
  { digit: '4', word: 'Four' },
  { digit: '5', word: 'Five' },
  { digit: '6', word: 'Six' },
  { digit: '7', word: 'Seven' },
  { digit: '8', word: 'Eight' },
  { digit: '9', word: 'Nine' },
];

export const distressCalls = {
  mayday: {
    title: 'MAYDAY (Distress)',
    priority: 'Highest',
    signal: 'Mayday (3x in call, 1x in message)',
    meaning: 'Vessel threatened by grave and imminent danger, requires IMMEDIATE assistance',
    channelCall: 'Channel 16 (VHF) or 2182 kHz (MF)',
    example: 'Mayday Mayday Mayday, this is Canadian Sailor, Canadian Sailor, Canadian Sailor...',
    steps: [
      'Assess the danger - only declare Mayday in grave/imminent danger',
      'Switch to Channel 16 (or 2182 kHz MF)',
      'Send DSC Distress alert (if equipped with DSC)',
      'Transmit voice Mayday call: "Mayday Mayday Mayday, this is [vessel name] [3x], over"',
      'Wait for acknowledgement',
      'Send Distress message: "Mayday [1x], [vessel name], position, nature of distress, persons on board, assistance available"',
      'Continue transmitting on Channel 16 until help arrives',
    ],
    silence: 'Seelonce Mayday (by vessel in distress) or Seelonce Distress (by others)',
    cancellation: 'Seelonce Feenee (when danger has passed)',
  },
  panpan: {
    title: 'PAN PAN (Urgency)',
    priority: 'High (below Distress)',
    signal: 'Pan Pan (3x in call)',
    meaning: 'Very urgent safety issue, assistance likely needed but not immediately',
    channelCall: 'Channel 16 (VHF) or 2182 kHz (MF)',
    example: 'Pan Pan Pan Pan Pan Pan, All Stations, this is Canadian Sailor...',
    steps: [
      'Assess the urgency - serious but not grave/imminent danger',
      'Switch to Channel 16',
      'Transmit: "Pan Pan Pan Pan Pan Pan, All Stations, this is [vessel name] [3x], over"',
      'Send urgency message with details of the situation',
      'Listen for responses and coast guard assistance',
    ],
    silence: 'Stations must listen for at least 3 minutes',
    cancellation: 'Broadcast "Urgency Ended" to All Stations when situation resolved',
  },
  securite: {
    title: 'SÉCURITÉ (Safety)',
    priority: 'Medium (below Distress/Urgency)',
    signal: 'Sécurité (3x in call)',
    meaning: 'Important navigational or weather warning',
    channelCall: 'Channel 16 call, then Channel 6 for detailed message',
    example: 'Sécurité Sécurité Sécurité, All Stations, this is Canadian Sailor...',
    steps: [
      'Identify the safety hazard (weather, navigation, etc.)',
      'Switch to Channel 16',
      'Transmit: "Sécurité Sécurité Sécurité, All Stations, this is [station] [3x], over"',
      'Switch to Channel 6',
      'Transmit the safety information (warning details, position if relevant)',
      'Safety calls are broadcasts - no reply expected',
    ],
    silence: 'Stations must stop routine traffic but no minimum listening period required',
    cancellation: 'No explicit cancellation - information transmitted once',
  },
};
